#############################################################################
# Makefile for building: cs
# Generated by qmake (2.01a) (Qt 4.6.2) on: dt. gen. 25 16:54:13 2011
# Project:  cs.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -unix -o Makefile cs.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-cli \
		sub-gui \
		sub-gen

cli//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cli/ || $(MKDIR) cli/ 
	cd cli/ && $(QMAKE) /home/pc11b/Escriptori/CDI/reconstructor/cli/cli.pro -unix -o $(MAKEFILE)
sub-cli-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cli/ || $(MKDIR) cli/ 
	cd cli/ && $(QMAKE) /home/pc11b/Escriptori/CDI/reconstructor/cli/cli.pro -unix -o $(MAKEFILE)
sub-cli: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE)
sub-cli-make_default-ordered: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) 
sub-cli-make_default: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) 
sub-cli-make_first-ordered: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) first
sub-cli-make_first: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) first
sub-cli-all-ordered: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) all
sub-cli-all: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) all
sub-cli-clean-ordered: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) clean
sub-cli-clean: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) clean
sub-cli-distclean-ordered: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cli-distclean: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cli-install_subtargets-ordered: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) install
sub-cli-install_subtargets: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) install
sub-cli-uninstall_subtargets-ordered: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-cli-uninstall_subtargets: cli//$(MAKEFILE) FORCE
	cd cli/ && $(MAKE) -f $(MAKEFILE) uninstall
gui//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /home/pc11b/Escriptori/CDI/reconstructor/gui/gui.pro -unix -o $(MAKEFILE)
sub-gui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /home/pc11b/Escriptori/CDI/reconstructor/gui/gui.pro -unix -o $(MAKEFILE)
sub-gui: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE)
sub-gui-make_default-ordered: gui//$(MAKEFILE) sub-cli-make_default-ordered  FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) 
sub-gui-make_default: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) 
sub-gui-make_first-ordered: gui//$(MAKEFILE) sub-cli-make_first-ordered  FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) first
sub-gui-make_first: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) first
sub-gui-all-ordered: gui//$(MAKEFILE) sub-cli-all-ordered  FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) all
sub-gui-all: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) all
sub-gui-clean-ordered: gui//$(MAKEFILE) sub-cli-clean-ordered  FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-gui-clean: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-gui-distclean-ordered: gui//$(MAKEFILE) sub-cli-distclean-ordered  FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gui-distclean: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gui-install_subtargets-ordered: gui//$(MAKEFILE) sub-cli-install_subtargets-ordered  FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) install
sub-gui-install_subtargets: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) install
sub-gui-uninstall_subtargets-ordered: gui//$(MAKEFILE) sub-cli-uninstall_subtargets-ordered  FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-gui-uninstall_subtargets: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) uninstall
gen//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gen/ || $(MKDIR) gen/ 
	cd gen/ && $(QMAKE) /home/pc11b/Escriptori/CDI/reconstructor/gen/gen.pro -unix -o $(MAKEFILE)
sub-gen-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gen/ || $(MKDIR) gen/ 
	cd gen/ && $(QMAKE) /home/pc11b/Escriptori/CDI/reconstructor/gen/gen.pro -unix -o $(MAKEFILE)
sub-gen: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE)
sub-gen-make_default-ordered: gen//$(MAKEFILE) sub-gui-make_default-ordered  FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) 
sub-gen-make_default: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) 
sub-gen-make_first-ordered: gen//$(MAKEFILE) sub-gui-make_first-ordered  FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) first
sub-gen-make_first: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) first
sub-gen-all-ordered: gen//$(MAKEFILE) sub-gui-all-ordered  FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) all
sub-gen-all: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) all
sub-gen-clean-ordered: gen//$(MAKEFILE) sub-gui-clean-ordered  FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) clean
sub-gen-clean: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) clean
sub-gen-distclean-ordered: gen//$(MAKEFILE) sub-gui-distclean-ordered  FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gen-distclean: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gen-install_subtargets-ordered: gen//$(MAKEFILE) sub-gui-install_subtargets-ordered  FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) install
sub-gen-install_subtargets: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) install
sub-gen-uninstall_subtargets-ordered: gen//$(MAKEFILE) sub-gui-uninstall_subtargets-ordered  FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-gen-uninstall_subtargets: gen//$(MAKEFILE) FORCE
	cd gen/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: cs.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile cs.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile cs.pro

qmake_all: sub-cli-qmake_all sub-gui-qmake_all sub-gen-qmake_all FORCE

make_default: sub-cli-make_default-ordered sub-gui-make_default-ordered sub-gen-make_default-ordered FORCE
make_first: sub-cli-make_first-ordered sub-gui-make_first-ordered sub-gen-make_first-ordered FORCE
all: sub-cli-all-ordered sub-gui-all-ordered sub-gen-all-ordered FORCE
clean: sub-cli-clean-ordered sub-gui-clean-ordered sub-gen-clean-ordered FORCE
distclean: sub-cli-distclean-ordered sub-gui-distclean-ordered sub-gen-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-cli-install_subtargets-ordered sub-gui-install_subtargets-ordered sub-gen-install_subtargets-ordered FORCE
uninstall_subtargets: sub-cli-uninstall_subtargets-ordered sub-gui-uninstall_subtargets-ordered sub-gen-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

